name: Cypress Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - uses: actions/checkout@v4

      - uses: cypress-io/github-action@v6
        with:
          start: npx http-server . -p 3000 -a 0.0.0.0
          wait-on: http://localhost:3000
