name: Cypress Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6